### ISSUE TITLE
docker-compose的一些坑

### ISSUE THREAD

**Issue by halsn** [halsn/blog#4]
最近被`docker-compose`整出了内伤，主要是一些细节，被坑的很惨。
1. docker-compose.yml中的environment下的字段不要用引号引起来，不然会造成解析错误，例如`URI="mongodb://mongo/demo`，mongodb连接时会将URI解析成'"mongodb://mongo/deml"'，正确的写法时`URI=mongodb://mongo/demo`
2. 使用links时，不同容器之间的地址会通过docker启动的DNS服务器解析，地址是`127.0.0.11`
```
version: "2"

services:
  web:
    build: .
    container_name: demo_server
    ports:
      - 5000:5000
    environment:
      - URI=mongodb://mongodb/proctest
    links:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - /data/db:/data/db
```
在demo-server容器中可以ping mongodb
